name: macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: Build & Test (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew update
          brew install cmake sqlite
      - name: Configure
        run: >
          cmake -B build
          -DSQLINQ_BUILD_TESTS=ON
          -DCMAKE_BUILD_TYPE=Debug
          -S ${{ github.workspace }}
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ctest --test-dir build --output-on-failure
    env:
      SQLINQ_SQLITE_DATABASE: ":memory:"

